// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFeuaBQbCNkq9IN_llYkaMA817VgVzknI',
    appId: '1:565159716218:web:aad6607e397407101222c3',
    messagingSenderId: '565159716218',
    projectId: 'wti-vendor-dashboard',
    authDomain: 'wti-vendor-dashboard.firebaseapp.com',
    storageBucket: 'wti-vendor-dashboard.firebasestorage.app',
    measurementId: 'G-348T6DM76F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4_ryA7WgwR7uin8-iMLrLfS4ufXhKA5s',
    appId: '1:565159716218:android:9bd33f5b798be2001222c3',
    messagingSenderId: '565159716218',
    projectId: 'wti-vendor-dashboard',
    storageBucket: 'wti-vendor-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAL6OK0n1sT3j2LifExmTzZ7Uw0djNo9Q',
    appId: '1:565159716218:ios:69ed02295315e5b91222c3',
    messagingSenderId: '565159716218',
    projectId: 'wti-vendor-dashboard',
    storageBucket: 'wti-vendor-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.wtiVendorDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAL6OK0n1sT3j2LifExmTzZ7Uw0djNo9Q',
    appId: '1:565159716218:ios:69ed02295315e5b91222c3',
    messagingSenderId: '565159716218',
    projectId: 'wti-vendor-dashboard',
    storageBucket: 'wti-vendor-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.wtiVendorDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFeuaBQbCNkq9IN_llYkaMA817VgVzknI',
    appId: '1:565159716218:web:ce17c05c4af6bd971222c3',
    messagingSenderId: '565159716218',
    projectId: 'wti-vendor-dashboard',
    authDomain: 'wti-vendor-dashboard.firebaseapp.com',
    storageBucket: 'wti-vendor-dashboard.firebasestorage.app',
    measurementId: 'G-KE26GZGR5B',
  );
}
